export const mockAnalyticsData = {
  kpis: {
    totalDownloads: 284750,
    weeklyGrowth: 18.2,
    activeUsers: 5680,
    repositories: 156,
    successRate: 98.7,
    averageBuildTime: 1.8,
  },
  stacks: {
    top: [
      { name: "React + JavaScript", count: 89, percentage: 42.3 },
      { name: "Next.js + Tailwind", count: 67, percentage: 31.9 },
      { name: "Vue + Vite", count: 28, percentage: 13.3 },
      { name: "Svelte + Kit", count: 16, percentage: 7.6 },
      { name: "Angular + RxJS", count: 10, percentage: 4.8 },
    ],
    usage: [
      { name: "Frontend", value: 58 },
      { name: "Full-stack", value: 28 },
      { name: "Backend", value: 14 },
    ],
    trends: [
      { month: "Oct", react: 180, vue: 95, angular: 45, svelte: 25 },
      { month: "Nov", react: 195, vue: 105, angular: 50, svelte: 30 },
      { month: "Dec", react: 210, vue: 115, angular: 55, svelte: 35 },
      { month: "Jan", react: 225, vue: 125, angular: 60, svelte: 40 },
    ],
  },
  packageManagers: [
    { name: "npm", count: 89, percentage: 52.9 },
    { name: "pnpm", count: 45, percentage: 26.8 },
    { name: "yarn", count: 28, percentage: 16.7 },
    { name: "bun", count: 6, percentage: 3.6 },
  ],
  performance: {
    buildTime: 1.8,
    bundleSize: 142,
    lighthouse: 98,
    firstContentfulPaint: 0.9,
    largestContentfulPaint: 1.2,
  },
  deployments: {
    total: 1247,
    successful: 1231,
    failed: 16,
    averageTime: 2.1,
    successRate: 98.7,
  },
  system: {
    nodeVersions: [
      { version: "20.x", count: 78 },
      { version: "18.x", count: 45 },
      { version: "16.x", count: 12 },
    ],
    os: [
      { name: "Linux", count: 67 },
      { name: "macOS", count: 23 },
      { name: "Windows", count: 10 },
    ],
  },
};

export const mockSponsorsData = {
  sponsors: [
    {
      id: "sponsor-1",
      name: "TechCorp Solutions",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=techcorp",
      amount: 500,
      tier: "Gold",
      duration: "6 months",
      frequency: "monthly" as const,
      startDate: "2024-07-15",
      website: "https://techcorp.dev",
      github: "https://github.com/techcorp",
      isActive: true,
      totalContributed: 3000,
      sponsorshipCount: 1,
      isPublic: true,
      location: "San Francisco, CA",
      company: "TechCorp Solutions",
    },
    {
      id: "sponsor-2",
      name: "DevTools Inc",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=devtools",
      amount: 250,
      tier: "Silver",
      duration: "4 months",
      frequency: "monthly" as const,
      startDate: "2024-09-01",
      website: "https://devtools.io",
      github: "https://github.com/devtools",
      isActive: true,
      totalContributed: 1000,
      sponsorshipCount: 1,
      isPublic: true,
      location: "Austin, TX",
      company: "DevTools Inc",
    },
    {
      id: "sponsor-3",
      name: "OpenSource Hero",
      avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=opensource",
      amount: 100,
      tier: "Bronze",
      duration: "8 months",
      frequency: "monthly" as const,
      startDate: "2024-05-20",
      website: "https://opensource.dev",
      github: "https://github.com/opensourcehero",
      isActive: true,
      totalContributed: 800,
      sponsorshipCount: 1,
      isPublic: true,
      location: "Berlin, Germany",
      company: "OpenSource Hero",
    },
  ],
  analytics: {
    totalAmount: 850,
    monthlyRecurring: 850,
    oneTimeAmount: 0,
    totalSponsors: 3,
    activeSponsors: 3,
    monthlyGrowth: 25.0,
    topTier: "Gold",
    averageAmount: 283,
    tierBreakdown: {
      Gold: 1,
      Silver: 1,
      Bronze: 1,
    },
    recentSponsors: 1,
    retentionRate: 100,
    lifetimeValue: 1600,
  },
  meta: {
    count: 3,
    hasRealData: false,
    isFallback: true,
    timestamp: new Date().toISOString(),
  },
};

export const mockTwitterData = {
  tweets: [
    {
      id: "tweet-1",
      text: "Just discovered js-stack! 🚀 This CLI tool is a game-changer for scaffolding full-stack apps. The TypeScript integration is seamless and the templates are modern. Highly recommend! #JavaScript #FullStack #TypeScript",
      user: {
        id: "user-1",
        name: "Sarah Developer",
        username: "sarah_dev",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sarah",
        verified: false,
        followers_count: 1250,
        following_count: 890,
        description:
          "Full-stack developer passionate about modern web technologies",
      },
      engagement: {
        likes: 47,
        retweets: 12,
        replies: 8,
        bookmarks: 23,
        views: 1250,
      },
      created_at: "2024-01-15T10:30:00Z",
      timestamp: "2h",
      url: "https://twitter.com/sarah_dev/status/tweet-1",
      reply_settings: "everyone",
      is_retweet: false,
      is_reply: false,
      media: [],
      hashtags: ["JavaScript", "FullStack", "TypeScript"],
      mentions: [],
      urls: [],
    },
    {
      id: "tweet-2",
      text: "Prototyped a SaaS application in just one weekend using js-stack! The generator and plugin architecture saved me hours of boilerplate setup. The Docker integration is chef's kiss 👌",
      user: {
        id: "user-2",
        name: "Alex Chen",
        username: "alexchen_dev",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=alex",
        verified: true,
        followers_count: 8900,
        following_count: 1200,
        description:
          "SaaS founder & full-stack developer | Building the future of web apps",
      },
      engagement: {
        likes: 156,
        retweets: 34,
        replies: 19,
        bookmarks: 67,
        views: 4200,
      },
      created_at: "2024-01-14T16:45:00Z",
      timestamp: "1d",
      url: "https://twitter.com/alexchen_dev/status/tweet-2",
      reply_settings: "everyone",
      is_retweet: false,
      is_reply: false,
      media: [],
      hashtags: [],
      mentions: [],
      urls: [],
    },
    {
      id: "tweet-3",
      text: "The CLI UX in js-stack is absolutely top-notch! 🎯 Sensible defaults, modern templates, and the interactive prompts make project setup a breeze. This is how CLI tools should be built.",
      user: {
        id: "user-3",
        name: "Frontend Fan",
        username: "frontend_fan",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=frontend",
        verified: false,
        followers_count: 3400,
        following_count: 2100,
        description: "Frontend developer | React enthusiast | UI/UX lover",
      },
      engagement: {
        likes: 89,
        retweets: 18,
        replies: 11,
        bookmarks: 34,
        views: 2100,
      },
      created_at: "2024-01-13T09:15:00Z",
      timestamp: "2d",
      url: "https://twitter.com/frontend_fan/status/tweet-3",
      reply_settings: "everyone",
      is_retweet: false,
      is_reply: false,
      media: [],
      hashtags: [],
      mentions: [],
      urls: [],
    },
    {
      id: "tweet-4",
      text: "js-stack + Vercel deployment = perfect combo! 🚀 Got my full-stack app deployed in minutes. The build optimization and static export features are exactly what I needed.",
      user: {
        id: "user-4",
        name: "Deploy Master",
        username: "deploy_master",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=deploy",
        verified: false,
        followers_count: 2100,
        following_count: 1800,
        description: "DevOps engineer | Deployment automation expert",
      },
      engagement: {
        likes: 67,
        retweets: 15,
        replies: 6,
        bookmarks: 28,
        views: 1800,
      },
      created_at: "2024-01-12T14:20:00Z",
      timestamp: "3d",
      url: "https://twitter.com/deploy_master/status/tweet-4",
      reply_settings: "everyone",
      is_retweet: false,
      is_reply: false,
      media: [],
      hashtags: [],
      mentions: [],
      urls: [],
    },
  ],
  meta: {
    query: "js-stack || vipinyadav9m",
    count: 4,
    hasRealData: false,
    isFallback: true,
    timestamp: new Date().toISOString(),
    next_token: "mock_next_token_456",
    rate_limit: {
      remaining: 95,
      reset_time: new Date(Date.now() + 15 * 60 * 1000).toISOString(),
    },
  },
};
export const simulateApiDelay = (ms: number = 300) =>
  new Promise((resolve) => setTimeout(resolve, ms));
