export interface PresetTemplate {
  id: string;
  name: string;
  description: string;
  stack: Record<string, string | string[] | boolean>;
}

export const PRESET_TEMPLATES: PresetTemplate[] = [
  {
    id: "nextjs-app",
    name: "Next.js Application",
    description:
      "Full-stack Next.js 15 with App Router, PostgreSQL, and authentication",
    stack: {
      frontend: ["nextjs"],
      backend: "none",
      database: "postgres",
      orm: "prisma",
      auth: "better-auth",
      addons: ["testing", "biome", "docker"],
      packageManager: "bun",
      git: "true",
      install: "true",
    },
  },
  {
    id: "express-api",
    name: "Express API",
    description:
      "Lightweight Express.js REST API with PostgreSQL and JWT authentication",
    stack: {
      frontend: [],
      backend: "express",
      database: "postgres",
      orm: "prisma",
      auth: "jwt",
      addons: ["testing", "docker", "biome"],
      packageManager: "npm",
      git: "true",
      install: "true",
    },
  },
  {
    id: "mern-stack",
    name: "MERN Stack",
    description:
      "MongoDB + Express + React + Node.js - Classic full-stack JavaScript application",
    stack: {
      frontend: ["react"],
      backend: "express",
      database: "mongodb",
      orm: "mongoose",
      auth: "jwt",
      addons: ["testing", "docker", "biome"],
      packageManager: "npm",
      git: "true",
      install: "true",
    },
  },
  {
    id: "nestjs-api",
    name: "NestJS API",
    description:
      "Enterprise-grade NestJS API with Prisma, Passport, and comprehensive testing",
    stack: {
      frontend: [],
      backend: "nestjs",
      database: "postgres",
      orm: "prisma",
      auth: "passport",
      addons: ["testing", "docker", "biome"],
      packageManager: "pnpm",
      git: "true",
      install: "true",
    },
  },
  {
    id: "vue-app",
    name: "Vue Application",
    description:
      "Modern Vue 3 application with Composition API, Vite, and testing",
    stack: {
      frontend: ["vue"],
      backend: "none",
      database: "none",
      orm: "none",
      auth: "none",
      addons: ["testing", "biome"],
      packageManager: "pnpm",
      git: "true",
      install: "true",
    },
  },
  {
    id: "nuxt-app",
    name: "Nuxt Application",
    description:
      "Full-stack Nuxt 3 application with server routes and authentication",
    stack: {
      frontend: ["nuxt"],
      backend: "none",
      database: "postgres",
      orm: "prisma",
      auth: "better-auth",
      addons: ["testing", "biome", "docker"],
      packageManager: "pnpm",
      git: "true",
      install: "true",
    },
  },
  {
    id: "mobile-app",
    name: "React Native App",
    description: "Cross-platform mobile app with Expo and backend API",
    stack: {
      frontend: ["react-native"],
      backend: "fastify",
      database: "postgres",
      orm: "prisma",
      auth: "jwt",
      addons: ["testing", "docker"],
      packageManager: "pnpm",
      git: "true",
      install: "true",
    },
  },
  {
    id: "optimal-monorepo",
    name: "Optimal Monorepo",
    description:
      "Next.js 15 + NestJS microservices + PostgreSQL + Prisma + Better Auth + Turborepo - Enterprise-grade monorepo",
    stack: {
      frontend: ["nextjs"],
      backend: "nestjs",
      database: "postgres",
      orm: "prisma",
      auth: "better-auth",
      addons: ["testing", "biome", "turborepo", "docker"],
      packageManager: "pnpm",
      git: "true",
      install: "true",
    },
  },
  {
    id: "optimal-fullstack",
    name: "Optimal Full-Stack",
    description:
      "Next.js 15 + PostgreSQL + Prisma + Better Auth + pnpm + Biome - Maximum performance and DX",
    stack: {
      frontend: ["nextjs"],
      backend: "none",
      database: "postgres",
      orm: "prisma",
      auth: "better-auth",
      addons: ["testing", "biome", "docker"],
      packageManager: "pnpm",
      git: "true",
      install: "true",
    },
  },
  {
    id: "fastify-api",
    name: "Fastify API",
    description:
      "High-performance Fastify REST API with PostgreSQL and authentication",
    stack: {
      frontend: [],
      backend: "fastify",
      database: "postgres",
      orm: "prisma",
      auth: "jwt",
      addons: ["testing", "docker", "biome"],
      packageManager: "pnpm",
      git: "true",
      install: "true",
    },
  },
  {
    id: "svelte-app",
    name: "Svelte Application",
    description: "Modern Svelte application with SvelteKit and authentication",
    stack: {
      frontend: ["svelte"],
      backend: "none",
      database: "postgres",
      orm: "prisma",
      auth: "better-auth",
      addons: ["testing", "biome", "docker"],
      packageManager: "pnpm",
      git: "true",
      install: "true",
    },
  },
  {
    id: "angular-app",
    name: "Angular Application",
    description: "Enterprise Angular application with RxJS and testing",
    stack: {
      frontend: ["angular"],
      backend: "none",
      database: "none",
      orm: "none",
      auth: "none",
      addons: ["testing"],
      packageManager: "npm",
      git: "true",
      install: "true",
    },
  },
  {
    id: "minimal-api",
    name: "Minimal API",
    description: "Lightweight Fastify API with SQLite - Perfect for prototypes",
    stack: {
      frontend: [],
      backend: "fastify",
      database: "sqlite",
      orm: "prisma",
      auth: "jwt",
      addons: ["testing", "biome"],
      packageManager: "bun",
      git: "true",
      install: "true",
    },
  },
];
